# Generated by Django 3.2.23 on 2024-03-08 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_auto_20240308_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='registation_open',
            new_name='registration_open',
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
