# Generated by Django 3.2.23 on 2024-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='course.CourseStudent'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
