# Generated by Django 3.2.23 on 2024-03-23 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_version', models.IntegerField()),
                ('course_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_students', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='course.course')),
                ('students', models.ManyToManyField(related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
