# Generated by Django 3.2.23 on 2024-02-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20240114_0048'),
        ('schedule', '0002_auto_20240130_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_times', to='schedule.classroom'),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_times', to='course.course'),
        ),
    ]
